CREATE TABLE IF NOT EXISTS admin (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email VARCHAR(255),
    password VARCHAR(255)
);

CREATE TABLE departments (
    id BIGINT PRIMARY KEY AUTO_INCREMENT,
    dept VARCHAR(255),
    description VARCHAR(255)
);


CREATE TABLE IF NOT EXISTS manager (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    first_name VARCHAR(255),
    last_name VARCHAR(255),
    email_id VARCHAR(255),
    password VARCHAR(255),
    gender VARCHAR(50),
    age INT,
    contact_no VARCHAR(50),
    experience VARCHAR(255),
    street VARCHAR(255),
    pincode VARCHAR(20),
    department_id BIGINT,
    CONSTRAINT fk_manager_department FOREIGN KEY (department_id) REFERENCES departments(id)
);


CREATE TABLE IF NOT EXISTS employee (
    id BIGINT PRIMARY KEY,
    first_name VARCHAR(255),
    last_name VARCHAR(255),
    email_id VARCHAR(255),
    password VARCHAR(255),
    gender VARCHAR(50),
    age INT,
    contact_no VARCHAR(50),
    experience VARCHAR(255),
    street VARCHAR(255),
    pincode VARCHAR(20),
    manager_id BIGINT,
    department_id BIGINT,
    CONSTRAINT fk_employee_manager FOREIGN KEY (manager_id) REFERENCES manager(id),
    CONSTRAINT fk_employee_department FOREIGN KEY (department_id) REFERENCES departments(id)
);

CREATE TABLE IF NOT EXISTS salary (
    id BIGINT PRIMARY KEY,
    basic_pay DOUBLE,
    hra DOUBLE,
    bonus DOUBLE,
    salary_month VARCHAR(20),
    salary_year INT,
    employee_id BIGINT,
    CONSTRAINT fk_salary_employee FOREIGN KEY (employee_id) REFERENCES employee(id)
);
